services:
  daiana:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-final
      args:
        NODE_ENV: ${NODE_ENV:-production}
    stdin_open: true
    tty: true
    volumes:
      - ./data:/app/data
      - ./generatedImages:/app/generatedImages
    environment:
      # Common Configuration
      NODE_ENV: ${NODE_ENV:-production}
      DAIANA_SERVER_PORT: ${DAIANA_SERVER_PORT:-3000}
      DAEMON_PROCESS: ${DAEMON_PROCESS:-true}
      
      # CORS & URLs
      CORS_ORIGIN: ${CORS_ORIGIN}
      WEB_URL: ${WEB_URL:-http://localhost:4173}
      
      # Venice AI Configuration
      VENICE_API_KEY: ${VENICE_API_KEY}
      IMAGE_VENICE_MODEL: ${IMAGE_VENICE_MODEL:-flux-dev}
      SMALL_VENICE_MODEL: ${SMALL_VENICE_MODEL:-llama-3.3-70b}
      MEDIUM_VENICE_MODEL: ${MEDIUM_VENICE_MODEL:-llama-3.3-70b}
      LARGE_VENICE_MODEL: ${LARGE_VENICE_MODEL:-llama-3.3-70b}
      
      # Discord Integration
      DISCORD_APPLICATION_ID: ${DISCORD_APPLICATION_ID}
      DISCORD_API_TOKEN: ${DISCORD_API_TOKEN}
      
      # Telegram Integration
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      
      # Twitter Integration
      TWITTER_DRY_RUN: ${TWITTER_DRY_RUN:-false}
      TWITTER_USERNAME: ${TWITTER_USERNAME}
      TWITTER_PASSWORD: ${TWITTER_PASSWORD}
      TWITTER_EMAIL: ${TWITTER_EMAIL}
      
      # Twitter Posting Configuration
      POST_INTERVAL_MIN: ${POST_INTERVAL_MIN}
      POST_INTERVAL_MAX: ${POST_INTERVAL_MAX}
      
      # Wallet Configuration
      WALLET_PRIVATE_KEY: ${WALLET_PRIVATE_KEY}
      WALLET_PUBLIC_KEY: ${WALLET_PUBLIC_KEY}
      
      # ElevenLabs Configuration
      ELEVENLABS_XI_API_KEY: ${ELEVENLABS_XI_API_KEY}
      ELEVENLABS_MODEL_ID: ${ELEVENLABS_MODEL_ID:-eleven_multilingual_v2}
      ELEVENLABS_VOICE_ID: ${ELEVENLABS_VOICE_ID:-21m00Tcm4TlvDq8ikWAM}
      ELEVENLABS_VOICE_STABILITY: ${ELEVENLABS_VOICE_STABILITY:-0.5}
      ELEVENLABS_VOICE_SIMILARITY_BOOST: ${ELEVENLABS_VOICE_SIMILARITY_BOOST:-0.9}
      ELEVENLABS_VOICE_STYLE: ${ELEVENLABS_VOICE_STYLE:-0.66}
      ELEVENLABS_VOICE_USE_SPEAKER_BOOST: ${ELEVENLABS_VOICE_USE_SPEAKER_BOOST:-false}
      ELEVENLABS_OPTIMIZE_STREAMING_LATENCY: ${ELEVENLABS_OPTIMIZE_STREAMING_LATENCY:-4}
      ELEVENLABS_OUTPUT_FORMAT: ${ELEVENLABS_OUTPUT_FORMAT:-pcm_16000}
    ports:
      - "3000:3000"
    init: true
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-final
      args:
        NODE_ENV: ${NODE_ENV:-production}
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      WEB_SERVER_PORT: ${WEB_SERVER_PORT:-4173}
      DAIANA_URL: ${DAIANA_URL:-http://localhost:3000}
      WEB_URL: ${WEB_URL:-http://localhost:4173}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost}
    ports:
      - "4173:4173"
    init: true
    restart: always