services:
  daiana:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-production}
    stdin_open: true
    tty: true
    volumes:
      - ./data:/app/data
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      VENICE_API_KEY: ${VENICE_API_KEY}
      IMAGE_VENICE_MODEL: ${IMAGE_VENICE_MODEL:-flux-dev}
      DISCORD_APPLICATION_ID: ${DISCORD_APPLICATION_ID}
      DISCORD_API_TOKEN: ${DISCORD_API_TOKEN}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TWITTER_DRY_RUN: ${TWITTER_DRY_RUN:-false}
      TWITTER_USERNAME: ${TWITTER_USERNAME}
      TWITTER_PASSWORD: ${TWITTER_PASSWORD}
      TWITTER_EMAIL: ${TWITTER_EMAIL}
      POST_INTERVAL_MIN: ${POST_INTERVAL_MIN}
      POST_INTERVAL_MAX: ${POST_INTERVAL_MAX}
      WALLET_PRIVATE_KEY: ${WALLET_PRIVATE_KEY}
      WALLET_PUBLIC_KEY: ${WALLET_PUBLIC_KEY}
      ELEVENLABS_XI_API_KEY: ${ELEVENLABS_XI_API_KEY}
      ELEVENLABS_MODEL_ID: ${ELEVENLABS_MODEL_ID:-eleven_multilingual_v2}
      ELEVENLABS_VOICE_ID: ${ELEVENLABS_VOICE_ID:-21m00Tcm4TlvDq8ikWAM}
      ELEVENLABS_VOICE_STABILITY: ${ELEVENLABS_VOICE_STABILITY:-0.5}
      ELEVENLABS_VOICE_SIMILARITY_BOOST: ${ELEVENLABS_VOICE_SIMILARITY_BOOST:-0.9}
      ELEVENLABS_VOICE_STYLE: ${ELEVENLABS_VOICE_STYLE:-0.66}
      ELEVENLABS_VOICE_USE_SPEAKER_BOOST: ${ELEVENLABS_VOICE_USE_SPEAKER_BOOST:-false}
      ELEVENLABS_OPTIMIZE_STREAMING_LATENCY: ${ELEVENLABS_OPTIMIZE_STREAMING_LATENCY:-4}
      ELEVENLABS_OUTPUT_FORMAT: ${ELEVENLABS_OUTPUT_FORMAT:-pcm_16000}
      SERVER_PORT: ${SERVER_PORT:-3000}
      VITE_SERVER_PORT: ${VITE_SERVER_PORT:-4173}
    ports:
      - "3000:3000"
      - "4173:4173"
    command: ["/bin/bash", "/app/docker-entrypoint.sh"]
    init: true
    restart: always